# Generated by Django 4.2.2 on 2023-06-23 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('address', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('phone_number', models.CharField(max_length=12)),
                ('zipcode', models.CharField(max_length=25)),
                ('rooms_available', models.IntegerField()),
                ('room_type', models.CharField(max_length=100)),
                ('image_one', models.ImageField(upload_to='photos/resorts')),
                ('image_two', models.ImageField(upload_to='photos/resorts')),
                ('image_three', models.ImageField(blank=True, null=True, upload_to='photos/resorts')),
                ('image_four', models.ImageField(blank=True, null=True, upload_to='photos/resorts')),
                ('pool_available', models.BooleanField()),
                ('wifi_available', models.BooleanField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
