# Generated by Django 4.2.2 on 2023-06-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_property_owner_alter_property_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image_four',
            field=models.ImageField(blank=True, null=True, upload_to='photos/property'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image_one',
            field=models.ImageField(upload_to='photos/property'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image_three',
            field=models.ImageField(blank=True, null=True, upload_to='photos/property'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image_two',
            field=models.ImageField(upload_to='photos/property'),
        ),
    ]
