# Generated by Django 4.2.2 on 2023-06-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_property_image_four_alter_property_image_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(max_length=500),
        ),
    ]
